version: '3.0'

services:

  # Container A
  redis:
    container_name: redis
    hostname: redis
    image: redis:alpine
    volumes:
      - ./redis-volume:/data
    networks:
      - app-network

  # Container B
  redis-commander:
    container_name: redis-commander
    hostname: redis-commander
    image: rediscommander/redis-commander:latest
    restart: always
    environment:
    - REDIS_HOSTS=local:redis:6379
    ports:
    - "8081:8081"
    networks:
      - app-network
    depends_on:
      - redis

  # Container C and D
  backend:
    build: ./backend/src
    container_name: backend
    networks:
      - app-network
    depends_on:
      - redis
    ports:
      - 5000:5000
     
  # Container E
  frontend:
    container_name: frontend
    build: ./frontend
    networks: 
      - app-network
    depends_on: 
      - backend
    volumes:
      - '.:/frontend'
      - '/frontend/node_modules'
    ports:
      - 3001:3000
    environment:
      - CHOKIDAR_USEPOLLING=true

networks:
  app-network:

